name: Build Aplication and Push Docker

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Obteniendo Codigo Fuente
        uses: actions/checkout@v3

      - name: Instalando Node v22
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Instalando Dependencias
        run: npm install

      - name: Configurando Ambiente
        env:
          PORT: ${{ secrets.PORT }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
         echo "PORT=${{ secrets.PORT }}
         DATABASE_URL=${{ secrets.DATABASE_URL }}
         " > ./.env

      - name: Buid Aplicacion
        run: npm run build

      - name: Iniciando Prisma Data Source
        run: npx prisma init --datasource-provider mysql

      - name: Cargando Schema Base de Datos
        run: npx prisma db pull

      - name:  Obteniendo Version
        id: get_version
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Configurando Docker
        uses: docker/setup-buildx-action@v2

      - name: Login Repositorio Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            --push -f Dockerfile \
            -t markitooo/venus_dedsec_cl:${{ env.VERSION }} .
